---
apiVersion: v1
kind: Pod
metadata:
 name: catalogue
 labels:
   name: catalogue
   tier: app
spec:
 containers:
 - name: catalogue
   imagePullPolicy: Always
   image: chakradhar933/catalogue:v1
   resources:
     requests:
      cpu: "100m"
      memory: "120Mi"
     limits:
       cpu: "100m"
       memory: "120Mi" 
---
apiVersion: v1
kind: Service
metadata:
 name: web-service
spec:
 type: LoadBalancer
 selector:
   name: catalogue
   tier: app
 ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080