---
apiVersion: v1
kind: Pod
metadata:
 name: mongodb
 labels:
   name: mongodb
   tier: db
spec:
 containers:
 - name: mongodb
   imagePullPolicy: Always
   image: chakradhar933/mongodb:v1
   resources:
    requests:
      cpu: "100m"
      memory: "120Mi"
    limits:
      cpu: "100m"
      memory: "120Mi" 
---
apiVersion: v1
kind: Service
metadata:
 name: mongo-service
spec:
 selector:
  name: mongodb
  tier: db
 ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017            