---
apiVersion: v1
kind: Pod
metadata:
 name: web
 labels:
   name: web
   tier: frontend
spec:
 containers:
 - name: web
   imagePullPolicy: Always
   image: chakradhar933/web:k8s-2
   resources:
     requests:
      cpu: "100m"
      memory: "120Mi"
     limits:
       cpu: "100m"
       memory: "120Mi" 
   ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: web-service
spec:
 type: LoadBalancer
 selector:
   name: web
   tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
